'''
Name:			Even Fibonacci numbers

Description:	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
				By starting with 1 and 2, the first 10 terms will be:

				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

				By considering the terms in the Fibonacci sequence whose values do not exceed
				four million, find the sum of the even-valued terms.

Answer:			4613732
'''

def Fibonacci(max_num):
	n, prev = 1, 1
	while n <= max_num:
		yield n
		n, prev = n + prev, n

print("Sum: {}".format(sum(i for i in Fibonacci(4000000) if i % 2 == 0)))
